### ISSUE TITLE
Hard to access widgets on phones

### ISSUE THREAD

**Issue by taoyouh** [maheshwaghmare/bhari#1]
Phone users have to scroll to bottom to access widgets.

**Comment by maheshwaghmare** [comment]
Do you mean on front end? If yes then we have left, right and both sidebars. In sidebar case it's always recommended to show content first and then sidebar widget's.

**Comment by taoyouh** [comment]
I know contents should show before widgets. But in mainpage, it is even very hard to scroll to the "login" link. 
The default themes have widgets shown as a hamburger menu on the top.

**Comment by maheshwaghmare** [comment]
Okay, But instead of sidebar login links. You can add the login, logout, register links in navigation menu.

You can use the filter `wp_nav_menu_items`. Or  plugin https://wordpress.org/plugins/baw-login-logout-menu/
